### ISSUE TITLE
Trying to contribute

### ISSUE THREAD

**Issue by rhanb** [NathanWalker/nativescript-ng2-magic#25]
Hi @NathanWalker ,

I need your module to work with angular-cli but it doesn't work with the last version, i modified the module that i made, largely inspired by yours, to make it work with latest version of angular. You can find it here: 

https://github.com/rhanbIT/nativescript-ng2-cli-magic

There is also a problem with the template you were using to create the nativesript project so i created a new one: 

https://github.com/rhanbIT/nativescript-ng2-cli-magic-template

I would like to include tests and everything to make it right but following your contributing's guideline `npm test` doesn't work, any steps actually worked.

Could i have some guidenance? 

I propose myself to maintain the module i created which is yours but only for angular-cli (i unfortunately don't have enough time to maintain for all types of projects).

Cheers from France

**Comment by rhanb** [comment]
Forget to tell you about my config:

Node v6.6.0
Npm v3.10.3


I also implemented the auto installation of nativescript-sass if the file angular-cli.json specify that the project use sass. But i still change the extension file in `StyleUrls` to `.css` since NativeScript doesn't support `.sass` directly.

**Comment by Jonatthu** [comment]
Is this project still live? or there is another plans for ng-cli?

**Comment by NathanWalker** [comment]
Hi @rhanbIT thank you so much helping here. 
I had paused some developments here mainly because I hope some tighter integrations can occur with angular cli soon per: https://github.com/angular/angular-cli/issues/698#issuecomment-271227616

However it's hard to say how soon that may happen so it would probably be worth updating a few things to make sure it's compliant with latest cli. I am very busy at moment while also preparing to move from OR > CA so won't be much help for another month, but could definitely entertain some PR's.

@Jonatthu please take the above into consideration; definitely still live if a PR could be provided allowing it to be compliant with latest cli version with hopes that within a couple months the issue stated above will provide more direct integration with angular cli (which was my hope all along before I created this plugin ;) ).

**Comment by NathanWalker** [comment]
Fixed here, note new repo and install:
https://github.com/wwwalkerrun/nativescript-ngx-magic
